# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
# No yarn_mappings: the build uses Mojang's official names. See build.gradle.
loader_version=0.16.14
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=com.corncan.automodfetcher
archives_base_name=automodfetcher

# Dependencies
fabric_api_version=0.92.11+1.20.1